name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Rename APK file with Date and Time
        run: |
          timestamp=$(date +%Y%m%d_%H%M)
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/SCRUB_RUSH_${timestamp}.apk
          echo "APK_NAME=SCRUB_RUSH_${timestamp}.apk" >> $GITHUB_ENV

      - name: Upload build outputs (APK)
        uses: actions/upload-artifact@v4
        with:
          name: scrub-rush-debug-apk
          path: app/build/outputs/apk/debug/${{ env.APK_NAME }}
